server:
  port: 8989
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
      routes:
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/inventory/**
          filters:
            - RewritePath=/inventory/?(?<segment>.*), /${segment}
  mvc:
    problemdetails:
      enabled: true
