name: "ecommerce"
services:
  inventory-service:
    image: hrushik09/ecommerce-inventory-service
    container_name: inventory-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:mysql://inventory-db:3306/inventory-db
      - DB_USERNAME=root
      - DB_PASSWORD=rootroot
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      inventory-db:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  api-gateway:
    image: hrushik09/ecommerce-api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - INVENTORY_SERVICE_URL=http://inventory-service:8081
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8989:8989"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  webapp:
    image: hrushik09/ecommerce-webapp
    container_name: webapp
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ECOMMERCE_API_GATEWAY_URL=http://api-gateway:8989
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  catalog-service:
    image: hrushik09/ecommerce-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:mysql://catalog-db:3306/catalog-db
      - DB_USERNAME=root
      - DB_PASSWORD=rootroot
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      catalog-db:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m