name: "ecommerce-infra"
services:
  inventory-db:
    image: mysql:8.0.34
    container_name: inventory-db
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: inventory-db
    ports:
      - "13306:3306"
    volumes:
      - inventory-db-volume:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 20s
      timeout: 15s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m
volumes:
  inventory-db-volume: { }